import * as L from 'lucide'

type IconNode = L.IconNode

// The closest Lucide icon for each SF Symbol, for platforms without SF Symbols (Linux).
const map: Record<string, IconNode> = {
  'arrow.clockwise': L.RotateCw,
  'arrow.counterclockwise': L.RotateCcw,
  'arrow.down': L.ArrowDown,
  'arrow.down.to.line': L.Download,
  'arrow.down.circle': L.CircleArrowDown,
  'arrow.down.right.and.arrow.up.left': L.Minimize2,
  'arrow.left': L.ArrowLeft,
  'arrow.left.arrow.right': L.ArrowLeftRight,
  'arrow.right': L.ArrowRight,
  'arrow.right.doc.on.clipboard': L.ClipboardCopy,
  'arrow.up.doc.on.clipboard': L.ClipboardPaste,
  'arrow.right.to.line': L.ArrowRightToLine,
  'arrow.triangle.2.circlepath': L.RefreshCw,
  'arrow.triangle.branch': L.GitBranch,
  'arrow.up': L.ArrowUp,
  'arrow.up.right.square': L.SquareArrowOutUpRight,
  'arrowshape.turn.up.left': L.Reply,
  'apple.logo': L.Apple,
  'bell.badge': L.BellDot,
  bolt: L.Zap,
  book: L.BookOpen,
  'book.closed': L.Book,
  'book.pages': L.BookOpenText,
  'bubble.left': L.MessageSquare,
  'bubble.left.and.bubble.right': L.MessagesSquare,
  calendar: L.Calendar,
  'chart.bar': L.ChartColumn,
  checklist: L.ListChecks,
  checkmark: L.Check,
  'checkmark.circle': L.CircleCheck,
  'checkmark.circle.fill': L.CircleCheck,
  'checkmark.seal': L.BadgeCheck,
  'chevron.down': L.ChevronDown,
  'chevron.left': L.ChevronLeft,
  'chevron.left.2': L.ChevronsLeft,
  'chevron.right': L.ChevronRight,
  'chevron.right.2': L.ChevronsRight,
  'chevron.up': L.ChevronUp,
  'chevron.up.chevron.down': L.ChevronsUpDown,
  circle: L.Circle,
  'circle.dotted': L.CircleDashed,
  clock: L.Clock,
  'clock.arrow.circlepath': L.History,
  cloud: L.Cloud,
  cpu: L.Cpu,
  'cursorarrow.motionlines': L.MousePointerClick,
  desktopcomputer: L.Monitor,
  'desktopcomputer.trianglebadge.exclamationmark': L.MonitorX,
  display: L.Monitor,
  'display.2': L.MonitorSmartphone,
  'display.trianglebadge.exclamationmark': L.MonitorX,
  doc: L.File,
  'doc.badge.plus': L.FilePlus,
  'doc.on.clipboard': L.Clipboard,
  'doc.on.clipboard.fill': L.Clipboard,
  'doc.on.doc': L.Copy,
  'doc.plaintext': L.FileText,
  'doc.richtext': L.FileText,
  'doc.text': L.FileText,
  'doc.zipper': L.FileArchive,
  ellipsis: L.Ellipsis,
  'ellipsis.circle': L.CircleEllipsis,
  exclamationmark: L.TriangleAlert,
  'exclamationmark.circle': L.CircleAlert,
  'exclamationmark.circle.fill': L.CircleAlert,
  'exclamationmark.triangle': L.TriangleAlert,
  'exclamationmark.triangle.fill': L.TriangleAlert,
  eye: L.Eye,
  'eye.slash': L.EyeOff,
  film: L.Film,
  folder: L.Folder,
  'gauge.with.dots.needle.33percent': L.Gauge,
  gearshape: L.Settings,
  globe: L.Globe,
  hammer: L.Hammer,
  'hand.point.up.left': L.Pointer,
  'hand.raised': L.Hand,
  'hand.raised.slash': L.HandMetal,
  'info.circle': L.Info,
  iphone: L.Smartphone,
  key: L.Key,
  'key.fill': L.KeyRound,
  'keyboard.chevron.compact.down': L.Keyboard,
  laptopcomputer: L.Laptop,
  link: L.Link,
  'list.bullet': L.List,
  'list.bullet.rectangle': L.ScrollText,
  'lock.display': L.MonitorDot,
  'lock.shield': L.ShieldCheck,
  macmini: L.Server,
  'macpro.gen3': L.Server,
  macstudio: L.Server,
  magnifyingglass: L.Search,
  mic: L.Mic,
  'mic.fill': L.Mic,
  'mic.slash': L.MicOff,
  'mic.slash.fill': L.MicOff,
  'minus.circle': L.CircleMinus,
  'music.note': L.Music,
  network: L.Network,
  pencil: L.Pencil,
  person: L.User,
  'person.2': L.Users,
  'person.crop.circle': L.CircleUser,
  'person.crop.circle.badge.checkmark': L.UserCheck,
  'person.crop.circle.badge.plus': L.UserPlus,
  'person.fill': L.User,
  'phone.down.fill': L.PhoneOff,
  photo: L.Image,
  'photo.on.rectangle': L.Images,
  pin: L.Pin,
  'pin.fill': L.Pin,
  'pin.slash': L.PinOff,
  'play.circle': L.CirclePlay,
  plus: L.Plus,
  'plus.circle': L.CirclePlus,
  'point.3.connected.trianglepath.dotted': L.Waypoints,
  power: L.Power,
  qrcode: L.QrCode,
  'record.circle': L.CircleDot,
  'rectangle.and.hand.point.up.left': L.MousePointer2,
  'rectangle.portrait.and.arrow.right': L.LogOut,
  'rotate.right': L.RotateCw,
  safari: L.Compass,
  'server.rack': L.Server,
  shippingbox: L.Package,
  'sidebar.left': L.PanelLeft,
  'slider.horizontal.3': L.SlidersHorizontal,
  sparkles: L.Sparkles,
  'speaker.slash.fill': L.VolumeX,
  'speaker.wave.2': L.Volume2,
  'speaker.wave.2.fill': L.Volume2,
  'square.and.arrow.up': L.Share,
  'square.and.pencil': L.SquarePen,
  'square.grid.2x2': L.LayoutGrid,
  'square.grid.3x3': L.Grid3x3,
  'square.on.square': L.Copy,
  star: L.Star,
  'stop.circle': L.CircleStop,
  'stop.fill': L.Square,
  terminal: L.Terminal,
  'text.bubble': L.MessageSquareText,
  tray: L.Inbox,
  trash: L.Trash2,
  waveform: L.AudioLines,
  wifi: L.Wifi,
  'wifi.slash': L.WifiOff,
  'wrench.and.screwdriver': L.Wrench,
  xmark: L.X,
  'xmark.circle': L.CircleX,
  'xmark.circle.fill': L.CircleX,
}

const cache = new Map<string, string>()

export function fallbackSvg(name: string): string {
  const hit = cache.get(name)
  if (hit !== undefined) return hit
  const node = map[name] ?? L.Circle
  const svg = node
    .map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}="${v}"`).join(' ')}/>`)
    .join('')
  cache.set(name, svg)
  return svg
}
